# Generated by Django 6.0 on 2026-02-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_announcement_admin_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='admin_name',
            new_name='admin',
        ),
    ]
