# Generated by Django 6.0 on 2026-01-25 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover_photo', models.ImageField(upload_to='project_covers/')),
                ('description', models.TextField()),
                ('duration', models.FloatField()),
                ('type', models.CharField(choices=[('SW', 'Software'), ('HW', 'Hardware'), ('AI', 'AI')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('innovator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_innovator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Algorithms',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Components',
            },
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Focuses',
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Frameworks',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Ai',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects_app.project')),
                ('dataset_link', models.URLField()),
                ('notebook_source_link', models.URLField()),
                ('algorithms', models.ManyToManyField(related_name='applies', to='projects_app.algorithm')),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has', to='projects_app.focus')),
            ],
            options={
                'verbose_name_plural': 'Ai',
            },
            bases=('projects_app.project',),
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects_app.project')),
                ('code', models.URLField()),
                ('skill_level', models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], max_length=20)),
                ('components', models.ManyToManyField(related_name='consists_of', to='projects_app.component')),
            ],
            options={
                'verbose_name_plural': 'Hardware',
            },
            bases=('projects_app.project',),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects_app.project')),
                ('source_link', models.URLField()),
                ('platform', models.CharField(choices=[('WEB', 'Web'), ('MOB', 'Mobile'), ('DES', 'Desktop'), ('CRS', 'Cross Platform')], max_length=10)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_with', to='projects_app.framework')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='built_with', to='projects_app.language')),
            ],
            options={
                'verbose_name_plural': 'Software',
            },
            bases=('projects_app.project',),
        ),
    ]
