# Generated by Django 6.0 on 2026-01-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('AI', 'AI')], max_length=10),
        ),
    ]
