# Generated by Django 6.0 on 2026-01-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('SW', 'Software'), ('HW', 'Hardware'), ('AI', 'AI')], max_length=10),
        ),
    ]
