# Generated by Django 6.0 on 2026-03-02 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='built_with', to='projects_app.language'),
        ),
    ]
