# Generated by Django 6.0 on 2026-03-02 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0004_alter_software_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai',
            name='focus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='has', to='projects_app.focus'),
        ),
        migrations.AlterField(
            model_name='software',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='written_with', to='projects_app.framework'),
        ),
    ]
