# Generated by Django 6.0 on 2026-03-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
