# Generated by Django 6.0 on 2025-12-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_field_name_alter_language_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('reader', 'Reader')], default='reader', max_length=10),
        ),
    ]
