# Generated by Django 6.0 on 2025-12-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('contributor', 'Contributor'), ('learner', 'Learner')], default='Learner', max_length=20),
        ),
    ]
