# Generated by Django 6.0 on 2025-12-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fields',
            field=models.ManyToManyField(blank=True, null=True, to='authentication.field'),
        ),
    ]
