# Generated by Django 6.0 on 2026-01-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='user',
            name='languages',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
