# Generated by Django 6.0 on 2026-01-21 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_field_user_languages_alter_user_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='user',
            name='languages',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
