# Generated by Django 6.0 on 2026-01-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
